### ISSUE TITLE
error when first child is comment

### ISSUE THREAD

**Issue by Gauntlet173** [laws-africa/cobalt#58]
Cobalt throws a value error if the first child of a document is a comment, which using the `cobalt.hierarchical.Act(text)` method. This is a feature of some of the official examples, which suggests that is probably allowed for under the spec.

**Comment by longhotsummer** [comment]
Can you provide an example breaking XML file?

**Comment by Gauntlet173** [comment]
https://github.com/oasis-open/legaldocml-akomantoso/blob/master/csprd02-part2-specs/csprd02-part2-specs-examples/uk_pga-2014-27-enacted-data.xml

**Comment by longhotsummer** [comment]
Confirmed:

```
$ python3
Python 3.8.12 (default, Aug 31 2021, 04:09:21)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cobalt import *
>>> a = Act("""<akomaNtoso xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/WD17 ../schemas/akomantoso30.xsd " xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0/WD17">
...     <!-- Original document http://www.legislation.gov.uk/ukpga/2014/27/pdfs/ukpga_20140027_en.pdf -->
...     <!-- Level of compliance 1 because the FRBR IRI are not compliant with the AKN specs -->
...
...     <act name="UnitedKingdomPublicGeneralAct"></act></akomaNtoso>""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/greg/coding/laws.africa/cobalt/cobalt/akn.py", line 245, in __init__
    super().__init__(xml)
  File "/Users/greg/coding/laws.africa/cobalt/cobalt/akn.py", line 63, in __init__
    self.root = self.parse(xml)
  File "/Users/greg/coding/laws.africa/cobalt/cobalt/akn.py", line 264, in parse
    raise ValueError(f"Expected {self.document_type} as first child of root element, but got {name} instead")
ValueError: Expected act as first child of root element, but got comment instead
```

**Comment by Gauntlet173** [comment]
Thanks!
